/// Copy ID — ramah, santai. Source of truth until GET /ui/bootstrap.
const Map<String, String> copyFallback = {
  'home.hero_title': 'Uang kamu',
  'home.income': 'Masuk',
  'home.expense': 'Keluar',
  'home.greeting': 'Hai',
  'home.subtitle': 'Saldo kamu, sepanjang waktu',
  'home.savings': 'Tabungan',
  'home.emergency': 'Dana darurat',
  'home.debt_running': 'Utang jalan',
  'home.ai': 'Teman AI',
  'home.ai_sub': 'Nanya apa aja soal duit',
  'home.debt_hub': 'Catatan utang',
  'home.debt_hub_sub': 'KPR & kartu kredit',
  'home.recent': 'Baru aja',
  'home.see_all': 'Lihat semua',
  'home.empty_tx': 'Belum ada transaksi. Yuk catat yang pertama!',
  'nav.dashboard': 'Beranda',
  'nav.transactions': 'Transaksi',
  'nav.budgets': 'Anggaran',
  'nav.reports': 'Laporan',
  'nav.profile': 'Profil',
  'tx.title': 'Transaksi',
  'tx.search': 'Cari catatan…',
  'tx.date_specific': 'Tanggal tertentu',
  'tx.date_range': 'Rentang tanggal',
  'tx.delete': 'Hapus transaksi?',
  'tx.empty': 'Sepi. Belum ada yang tercatat.',
  'tx.add': 'Catat transaksi',
  'tx.photo': 'Fotoin struk',
  'tx.gallery': 'Ambil dari galeri',
  'budget.title': 'Anggaran',
  'budget.delete': 'Hapus anggaran?',
  'budget.empty': 'Belum pasang limit. Yuk bikin biar gak jebol.',
  'report.title': 'Laporan',
  'profile.title': 'Profil',
  'profile.logout': 'Keluar',
  'profile.logout_q': 'Yakin mau keluar dulu?',
  'profile.delete_account': 'Hapus akun',
  'debt.title': 'Catatan utang',
  'debt.kpr': 'Rumah (KPR)',
  'debt.kpr_sub': 'Hitung cicilan, cobain bunga beda-beda. Santai, ini simulasi.',
  'debt.cc': 'Kartu kredit',
  'debt.cc_sub': 'Jejak belanja, cicilan, dan tanggal tagihan.',
  'kpr.title': 'Simulasi KPR',
  'kpr.new': 'KPR baru',
  'kpr.delete': 'Hapus simulasi?',
  'kpr.extra': 'Bayar lebih',
  'cc.title': 'Kartu kredit',
  'cc.add': 'Tambah kartu',
  'cc.delete': 'Hapus kartu?',
  'ai.title': 'Teman AI',
  'ai.disclaimer': 'Ini saran mesin, bukan nasihat keuangan resmi ya.',
  'auth.login': 'Masuk',
  'auth.register': 'Daftar',
  'common.cancel': 'Batal',
  'common.save': 'Simpan',
  'common.delete': 'Hapus',
  'common.retry': 'Coba lagi',
  'common.share_hh': 'Biar keluarga juga lihat',
  'common.share_hh_sub': 'Kelihatan buat semua anggota rumah',
  'cat.manage': 'Atur kategori',
  'transfer.title': 'Pindahin saldo',
  'transfer.confirm': 'Kirim sekarang?',
};

String t(String key) => copyFallback[key] ?? key;
