/// Copy ID — ramah, santai. Live catalog is GET /ui/bootstrap (DB). This map is offline fallback.
import 'copy_fallback_en.dart';
export 'copy_fallback_en.dart';

const Map<String, String> copyFallback = {
  'home.hero_title': 'Uang kamu',
  'home.hero_sub': 'Rekap pribadi, dari awal sampai sekarang',
  'home.income': 'Pemasukan',
  'home.expense': 'Pengeluaran',
  'home.greeting': 'Hai',
  'home.greeting_sub': 'Saldo kamu, sepanjang waktu',
  'home.savings': 'Simpanan',
  'home.emergency': 'Dana darurat',
  'home.debt_running': 'Utang berjalan',
  'home.ai': 'Teman AI',
  'home.ai_sub': 'Nanya apa aja soal duit',
  'home.debt_hub': 'Catatan utang',
  'home.debt_hub_sub': 'KPR & kartu kredit',
  'home.recent': 'Baru saja',
  'home.see_all': 'Lihat semua',
  'home.empty_tx': 'Belum ada transaksi. Yuk catat yang pertama!',
  'nav.dashboard': 'Beranda',
  'nav.transactions': 'Transaksi',
  'nav.budgets': 'Anggaran',
  'nav.reports': 'Laporan',
  'nav.profile': 'Profil',
  'tx.title': 'Transaksi',
  'tx.search': 'Cari catatan…',
  'tx.filter_all': 'Semua',
  'tx.filter_out': 'Pengeluaran',
  'tx.filter_in': 'Pemasukan',
  'tx.categories': 'Kategori',
  'tx.sort': 'Urutkan',
  'tx.sort_newest': 'Terbaru',
  'tx.sort_oldest': 'Terlama',
  'tx.sort_high': 'Nominal besar',
  'tx.sort_low': 'Nominal kecil',
  'tx.date': 'Tanggal',
  'tx.date_specific': 'Tanggal tertentu',
  'tx.date_range': 'Rentang tanggal',
  'tx.date_clear': 'Hapus filter',
  'tx.delete': 'Hapus transaksi?',
  'tx.empty': 'Sepi. Belum ada yang tercatat.',
  'tx.add': 'Catat transaksi',
  'tx.new': 'Catatan baru',
  'tx.edit_title': 'Ubah catatan',
  'tx.kind_out': 'PENGELUARAN',
  'tx.kind_in': 'PEMASUKAN',
  'tx.for': 'Untuk apa',
  'tx.for_hint': 'Sate padang, Grab, gaji…',
  'tx.note_opt': 'Catatan (opsional)',
  'tx.note_hint': 'Tambah catatan…',
  'tx.update': 'Simpan perubahan',
  'tx.scan_title': 'Ambil struk',
  'tx.scan_sub': 'Kamera atau dari galeri',
  'tx.recorded': 'Tercatat',
  'tx.updated': 'Sudah diubah',
  'tx.amount_err': 'Isi jumlah dulu',
  'tx.cat_err': 'Pilih kategori dulu',
  'tx.save_fail': 'Gagal simpan. Coba lagi.',
  'tx.processing': 'Struk lagi diproses…',
  'tx.processing_sub': 'Sebentar ya',
  'tx.photo': 'Fotoin struk',
  'tx.gallery': 'Ambil dari galeri',
  'budget.title': 'Anggaran',
  'budget.delete': 'Hapus anggaran?',
  'budget.empty': 'Belum pasang limit. Yuk bikin biar gak jebol.',
  'budget.empty_title': 'Belum ada anggaran bulan ini',
  'budget.empty_hint': 'Tap + buat pasang limit per kategori',
  'budget.suggest_btn': 'Minta saran',
  'budget.overview': 'Ringkasan anggaran',
  'budget.total': 'Total anggaran',
  'budget.spent': 'Sudah dipakai',
  'budget.remaining': 'Sisa',
  'budget.income': 'Total pemasukan',
  'budget.over_by': 'Anggaran lebih besar dari pemasukan, lebihan {n}',
  'budget.covered': 'Pemasukan cukup buat semua anggaran (sisa {n})',
  'budget.shortfall': 'Kurang {n}',
  'budget.outside': 'Di luar anggaran',
  'budget.outside_hint': 'Ada pengeluaran di kategori yang belum dipasang limit. Pasang biar kepantau.',
  'budget.edit': 'Ubah anggaran',
  'budget.set': 'Pasang limit bulanan',
  'budget.pick_cat': 'Pilih kategori',
  'budget.limit': 'Limit bulanan',
  'budget.cycle_day': 'Tanggal mulai siklus',
  'budget.pick_day': 'Pilih tanggal',
  'budget.day_n': 'Tanggal {n}',
  'budget.cycle_hint': 'Pengeluaran dihitung dari tanggal ini bulan lalu sampai sehari sebelum tanggal ini bulan ini.',
  'budget.update': 'Simpan perubahan',
  'budget.save': 'Pasang anggaran',
  'budget.remove_q': 'Hapus anggaran {c}?',
  'budget.over_by_short': 'Lebih {n}',
  'budget.exhausted': 'Limit habis',
  'budget.remaining_n': 'Sisa {n}',
  'report.title': 'Laporan',
  'profile.title': 'Profil',
  'profile.cycle_day': 'Tanggal mulai siklus',
  'profile.cycle_hint': 'Siklus tagihan kamu jalan dari tanggal {n} sampai tanggal {n-1} bulan depan.',
  'profile.edit': 'Ubah profil',
  'profile.change_pass': 'Ganti sandi',
  'profile.sec_account': 'Setelan akun',
  'profile.sec_features': 'Fitur',
  'profile.sec_cycle': 'Siklus tagihan',
  'profile.sec_look': 'Tampilan',
  'profile.sec_actions': 'Aksi akun',
  'profile.debt_tracker': 'Catatan utang',
  'profile.copy_admin': 'Kelola Copy',
  'profile.copy_search': 'Cari key atau teks…',
  'profile.config_admin': 'Setelan Config',
  'profile.config_format': 'Format uang',
  'profile.config_prefix': 'Awalan (prefix)',
  'profile.config_group': 'Pemisah ribuan',
  'profile.config_decimal': 'Pemisah desimal',
  'profile.config_flags': 'Fitur flags',
  'profile.config_home_flag': 'Home pribadi all-time (true/false)',
  'profile.config_theme': 'Warna tema',
  'profile.config_theme_hint': 'Preset warna yang sudah diaudit kontrasnya. Pilih, simpan, warnanya langsung ganti live.',
  'profile.edit_name': 'Ubah nama tampilan',
  'profile.name_hint': 'Nama tampilan baru',
  'profile.cur_pass': 'Sandi sekarang',
  'profile.new_pass': 'Sandi baru',
  'profile.confirm_pass': 'Ulangi sandi baru',
  'profile.required': 'Wajib diisi',
  'profile.theme_system': 'Ikut sistem',
  'profile.theme_light': 'Terang',
  'profile.theme_dark': 'Gelap',
  'profile.delete_forever': 'Hapus permanen',
  'hh.title': 'Keluarga',
  'hh.join': 'Gabung keluarga',
  'hh.join_btn': 'Gabung',
  'hh.joining': 'Lagi gabung…',
  'hh.invite_code': 'Kode undangan',
  'hh.create': 'Buat keluarga baru',
  'hh.create_btn': 'Buat',
  'hh.create_new': 'Buat baru',
  'hh.name': 'Nama keluarga',
  'hh.default_name': 'Keluarga',
  'hh.members': 'Anggota',
  'profile.cycle_pill': 'Tanggal {n}',
  'profile.family_n': '{n} orang',
  'hh.join_hint': 'Isi kode undangan dari admin keluarga.',
  'hh.joined': 'Gabung keluarga berhasil',
  'hh.created': 'Keluarga berhasil dibuat',
  'hh.code_copied': 'Kode undangan disalin',
  'hh.code_label': 'Kode {c}',
  'hh.invite_hint': 'contoh ABC12345',
  'hh.name_hint': 'contoh Keluarga Filla',
  'profile.delete_warn': 'Akun dan semua catatan duit kehapus permanen. Gak bisa dibalikin.',
  'profile.delete_type': 'Ketik HAPUS buat konfirmasi:',
  'profile.delete_word': 'HAPUS',
  'profile.logout': 'Keluar',
  'profile.logout_q': 'Yakin mau keluar dulu?',
  'profile.delete_account': 'Hapus akun',
  'debt.title': 'Catatan utang',
  'debt.kpr': 'Rumah (KPR)',
  'debt.kpr_sub': 'Hitung cicilan, cobain bunga beda-beda. Santai, ini simulasi.',
  'debt.cc': 'Kartu kredit',
  'debt.cc_sub': 'Jejak belanja, cicilan, dan tanggal tagihan.',
  'kpr.title': 'Simulasi KPR',
  'kpr.new': 'KPR baru',
  'kpr.delete': 'Hapus simulasi?',
  'kpr.extra': 'Bayar lebih',
  'kpr.no_schedule': 'Belum ada jadwal cicilan',
  'cc.title': 'Kartu kredit',
  'cc.add': 'Tambah kartu',
  'cc.delete': 'Hapus kartu?',
  'cc.del_txn': 'Hapus transaksi?',
  'cc.del_inst': 'Hapus cicilan?',
  'cc.txn_gone': 'Transaksi kehapus',
  'cc.inst_gone': 'Cicilan kehapus',
  'ai.title': 'Teman AI',
  'ai.disclaimer': 'Ini saran mesin, bukan nasihat keuangan resmi ya.',
  'ai.hint': 'Nanya soal duit…',
  'auth.login': 'Masuk',
  'auth.register': 'Daftar',
  'auth.hi': 'Halo sob, WealthTrack disini',
  'auth.tagline': 'Catat duit, tanpa drama',
  'auth.username': 'Username',
  'auth.email': 'Email',
  'auth.password': 'Kata sandi',
  'auth.password_again': 'Ulangi sandi',
  'auth.display_name': 'Nama tampilan',
  'auth.otp': 'Kode OTP',
  'auth.otp_hint': '6 digit dari email',
  'auth.send_otp': 'Kirim kode',
  'auth.sending_otp': 'Lagi dikirim…',
  'auth.otp_sent': 'Kode udah dikirim ke emailmu',
  'auth.register_hi': 'Yuk daftar',
  'auth.register_sub': 'Sebentar aja, terus bisa catat duit.',
  'auth.have_account': 'Sudah punya akun? Masuk aja',
  'auth.no_account': 'Belum punya akun? Daftar dulu',
  'auth.err_user': 'Minimal 3 huruf',
  'auth.err_pass': 'Minimal 6 karakter',
  'auth.err_email': 'Emailnya belum bener',
  'auth.err_display': 'Nama tampilan wajib diisi',
  'auth.err_match': 'Sandi belum sama',
  'auth.err_otp': 'Isi 6 digit dulu',
  'common.cancel': 'Batal',
  'common.save': 'Simpan',
  'common.delete': 'Hapus',
  'common.retry': 'Coba lagi',
  'common.required': 'Wajib diisi',
  'common.positive': 'Isi angka di atas 0',
  'common.share_hh': 'Biar keluarga juga lihat',
  'common.share_hh_sub': 'Kelihatan buat semua anggota keluarga',
  'cat.manage': 'Kelola kategori',
  'transfer.title': 'Pindahin saldo',
  'transfer.recipients': 'Penerima',
  'transfer.add_hint': 'Tap Tambah buat pilih penerima',
  'transfer.confirm': 'Kirim sekarang?',
  'transfer.send': 'Kirim',
  'transfer.sending': 'Lagi diproses…',
  'transfer.no_members': 'Belum ada anggota keluarga',
  'transfer.ok': 'Berhasil! {n} pasang transaksi tercatat.',
  'transfer.fail': 'Gagal kirim',
  'transfer.amount_positive': 'Jumlah buat {name} harus lebih dari 0',
  'transfer.add_recipient': 'Tambah minimal satu penerima',
  'transfer.add': 'Tambah',
  'profile.updated': 'Profil kesimpen',
  'profile.pass_ok': 'Sandi berhasil diganti',
  'sort.title': 'Urutin',
  'sort.newest': 'Paling baru',
  'sort.oldest': 'Paling lama',
  'sort.highest': 'Paling gede',
  'sort.lowest': 'Paling kecil',
  'sort.name_az': 'Nama A–Z',
  'sort.name_za': 'Nama Z–A',
  'tx.deleted': 'Transaksi kehapus',
  'tx.del_fail': 'Gagal hapus transaksi',
  'tx.no_other_member': 'Belum ada anggota keluarga lain',
  'common.edit': 'Ubah',
  'common.change_owner': 'Ganti pemilik',
  'common.new': 'Buat baru',
  'suggest.title': 'Saran anggaran',
  'suggest.empty': 'Belum ada saran',
  'suggest.empty_sub': 'Catat transaksi dulu, nanti aku bikinin limitnya.',
  'suggest.picked': 'dipilih',
  'suggest.all': 'Pilih semua',
  'suggest.clear': 'Kosongin',
  'suggest.apply': 'Pasang',
  'suggest.avg': 'Rata-rata',
  'suggest.existing': 'Sudah ada',
  'suggest.amount': 'Usulan',
  'report.income': 'Pemasukan',
  'report.expense': 'Pengeluaran',
  'report.balance': 'Sisa',
  'report.savings_rate': 'Simpanan',
  'report.daily_avg': 'Rata-rata/hari',
  'report.vs_budget': 'Anggaran vs real',
  'report.by_cat': 'Per kategori',
  'report.compare_cat': 'Banding kategori',
  'report.trend': 'Tren bulanan',
  'report.daily': 'Per hari',
  'report.hh_split': 'Bagi keluarga',
  'report.hh_cat': 'Kategori keluarga',
  'report.hh_daily': 'Harian keluarga',
  'report.export': 'Unduh Excel setahun',
  'cat.add': 'Kategori baru',
  'cat.edit': 'Ubah kategori',
  'cat.name': 'Nama',
  'cat.icon': 'Ikon',
  'cat.icon_search': 'Cari ikon (id / nama)',
  'cat.keywords': 'Kata kunci',
  'cat.keywords_hint': 'pisah pakai koma',
  'cat.type': 'Tipe',
  'cat.default_locked': 'Kategori bawaan gak bisa diubah.',
  'cat.save': 'Simpan',
  'cat.create': 'Tambah',
  'cat.empty': 'Belum ada kategori',
  'cat.search': 'Cari kategori…',
  'cat.delete_confirm': 'Hapus kategori ini? Kategori yang sudah dipakai transaksi tetap aman dan gak bisa dihapus.',
  'cat.fail': 'Gagal',
  'home.empty_tx_short': 'Belum ada transaksi',
  'cc.summary': 'Ringkasan',
  'cc.empty': 'Belum ada kartu kredit',
  'cc.empty_tx': 'Belum ada transaksi',
  'cc.empty_installments': 'Belum ada cicilan',
  'cc.proj_next': 'Proyeksi bulan depan',
  'kpr.extra_payment': 'Pembayaran ekstra',
  'kpr.schedule': 'Jadwal cicilan',
  'kpr.extra_detail': 'Detail pembayaran ekstra',
  'kpr.compare': 'Lihat perbandingan',
  'kpr.pick_option': 'Pilih yang kamu mau',
  'kpr.diff': 'Selisih',
  'kpr.extra_deleted': 'Pembayaran ekstra kehapus',
  'kpr.empty': 'Belum ada simulasi KPR',
  'cat.empty_picker': 'Kategori belum ada',
  'common.close': 'Tutup',
  'common.result': 'Hasil hitungan',
  'common.calculate': 'Hitung',
  'common.add_period': 'Tambah periode',
  'common.year_n': '{n} tahun',
  'common.day_n_short': 'Tanggal {n}',
  'common.from_month': 'Dari (bln)',
  'common.to_month': 'Sampai (bln)',
  'common.rate_pct': 'Bunga %',
  'common.type': 'Tipe',
  'common.fixed': 'Tetap',
  'common.floating': 'Mengambang',
  'common.graduated': 'Bertahap',
  'common.mix': 'Campur',
  'common.total': 'Total',
  'common.from': 'Dari',
  'common.apply': 'Terapin',
  'common.clear_all': 'Kosongin',
  'common.all_cat': 'Semua kategori',
  'common.filter_cat': 'Saring kategori',
  'common.select_owner': 'Pilih pemilik baru',
  'common.owner_changed': 'Pemiliknya ganti ke {name}',
  'common.failed': 'Gagal',
  'common.failed_download': 'Gagal unduh',
  'common.making_file': 'Lagi bikin file…',
  'common.export_year': 'Ekspor WealthTrack {year}',
  'common.thinking': 'Lagi mikir…',
  'common.try_again': 'Gagal — tap buat coba lagi',
  'common.not_found': 'Gak ketemu',
  'common.empty': 'Kosong',
  'common.saved': 'Kesimpen',
  'common.saved_live': 'Kesimpen. Live tanpa build.',
  'common.check_input': 'Cek lagi isiannya ya.',
  'common.delete_fail': 'Gagal hapus',
  'ai.sample1': '"Bulan ini makan berapa, ya?"',
  'ai.sample2': '"Kasih tips nabung dong"',
  'cc.tab_txn': 'Transaksi',
  'cc.tab_inst': 'Cicilan',
  'cc.card_saved': 'Kartu kesimpen',
  'cc.inst_saved': 'Cicilan kesimpen',
  'cc.inst_add': 'Tambah cicilan',
  'cc.total_positive': 'Total harus lebih dari 0',
  'cc.monthly_positive': 'Cicilan bulanan harus lebih dari 0',
  'cc.card_hint': 'mis. Mandiri Visa Platinum',
  'cc.last4_hint': 'mis. 1234',
  'cc.inst_hint': 'mis. Cicilan MacBook',
  'cc.months_hint': 'mis. 12',
  'cc.amount_hint': 'Rp 0',
  'cc.desc_label': 'Keterangan',
  'cc.desc_hint': 'mis. belanja',
  'cc.amount_label': 'Jumlah',
  'cc.date_label': 'Tanggal',
  'cc.not_found': 'Kartu gak ketemu',
  'cc.delete_confirm_body': 'Hapus "{label}"? Gak bisa dibalikin.',
  'kpr.house_price': 'Harga rumah',
  'kpr.loan': 'Pinjaman',
  'kpr.installment': 'Cicilan / bulan',
  'kpr.total_interest': 'Total bunga',
  'kpr.total_payment': 'Total bayar',
  'kpr.sim_not_found': 'Simulasi gak ketemu',
  'kpr.sim_deleted': 'Simulasi kehapus',
  'kpr.sim_delete_fail': 'Gagal hapus simulasi',
  'kpr.sim_saved': 'Simulasi kesimpen',
  'kpr.fill_price_dp': 'Isi harga rumah sama uang muka dulu ya',
  'kpr.calc_failed': 'Gagal hitung. Coba lagi ya',
  'kpr.loan_positive': 'Nilai pinjaman harus lebih dari 0',
  'kpr.name_hint': 'mis. Rumah Impian',
  'kpr.rate_hint': 'mis. 9.0',
  'kpr.rate_low_hint': 'mis. 7.0',
  'kpr.increment_hint': 'mis. 0.5',
  'kpr.months_hint': 'mis. 12',
  'kpr.extra_saved': 'Pembayaran ekstra kesimpen',
  'kpr.extra_fail': 'Gagal pasang pembayaran ekstra',
  'kpr.extra_amount': 'Jumlah pembayaran ekstra (Rp)',
  'kpr.extra_apply_month': 'Pasang di bulan ke',
  'kpr.option_a': 'A. Cicilan lebih kecil',
  'kpr.option_a_sub': 'Tenor tetap, cicilan turun',
  'kpr.option_b': 'B. Tenor lebih pendek',
  'kpr.option_b_sub': 'Cicilan tetap, lunas lebih cepet',
  'kpr.period_label': 'Tenor baru',
  'kpr.period_n': 'Periode {n}',
  'kpr.interest_saved': 'Bunga dihemat',
  'kpr.paid_off': 'Lunas',
  'kpr.date_in_month': 'Tanggal dalam bulan',
  'home.savings_pocket': 'Simpanan',
  'home.emergency_pocket': 'Dana darurat',
  'profile.saved': 'Profil kesimpen',
  'profile.cycle_saved': 'Siklus tagihan kesimpen',
  'profile.admin': 'admin',
  'debt.empty_hint': 'Pilih yang mau diurus. Gak usah tegang — ini catetan, bukan bank.',
  'hh.member_badge': '🏠 Anggota',
  'cc.empty_add': 'Tap + buat nambah kartu kredit',
  'cc.delete_card': 'Hapus "{label}"? Transaksi dan cicilannya ikut kehapus.',
  'cc.inst_note': '{count} cicilan · {amount} perkiraan',
  'cc.inst_progress': '{done} / {total} bulan',
  'kpr.empty_add': 'Tap + buat simulasi KPR pertama',
  'kpr.due_label': 'Bulan ke-{month} dari {total} · {amount} jatuh tempo',
  'kpr.extra_intro': 'Pembayaran ekstra ngepotong pokok pinjaman langsung. Bisa pilih cicilan lebih kecil atau tenor lebih pendek.',
  'kpr.extra_pick': 'Dua opsi sama-sama ngecilin sisa pinjaman. Pilih yang pas.',
  'kpr.extra_result': 'Cicilan: {installment}/bulan lebih kecil (Opsi A) · Tenor: {months} bulan lebih cepet (Opsi B)',
  'kpr.extra_delete': 'Hapus pembayaran ekstra {amount} di bulan ke-{month}? Jadwalnya dihitung ulang. Gak bisa dibalikin.',
  'kpr.no_extra': 'Belum ada pembayaran ekstra. Tap ikon uang di atas buat nambah.',
  'kpr.extra_applied': 'Hitungan cicilan & tenor baru mulai {start} — {end}',
  'kpr.interest_year': 'Bunga: {amount}',
  'kpr.year_label': 'Tahun {n}',
  'tx.delete_confirm': 'Hapus "{label}"? Gak bisa dibalikin.',
  'tx.this_note': 'catatan ini',
  'home.ocr_processing': '{count} transaksi sedang diproses…',
  'home.member_count': '{n} orang',
  'reports.empty_month': 'Bulan ini sepi, belum ada catatan',
  'profile.app_version': 'WealthTrack v1.0.0',
  'cc.inst_active': 'Cicilan aktif',
  'cc.per_month': 'Per bulan',
  'cc.name_label': 'Nama kartu',
  'cc.last4_label': '4 digit terakhir (opsional)',
  'cc.limit_label': 'Limit kredit',
  'cc.monthly_label': 'Cicilan / bulan',
  'cc.inst_months_label': 'Jumlah bulan',
  'cc.start_month_label': 'Bulan mulai',
  'kpr.name_label': 'Nama simulasi',
  'kpr.dp_label': 'Uang muka (DP)',
  'kpr.loan_auto': 'Pinjaman (otomatis)',
  'kpr.tenor_label': 'Tenor',
  'kpr.first_label': 'Cicilan pertama',
  'kpr.due_date_label': 'Tanggal jatuh tempo',
  'kpr.type_label': 'Tipe bunga',
  'kpr.base_rate_label': 'Bunga dasar (%)',
  'kpr.incr_label': 'Kenaikan per periode (%)',
  'kpr.period_months_label': 'Lama periode (bulan)',
  'kpr.periods_label': 'Periode bunga',
  'cc.total_limit': 'Total limit',
  'cc.due_label': 'Jatuh tempo',
  'cc.bill_label': 'Tanggal tagihan',
  'cc.this_card': 'kartu ini',
  'cc.no_number': 'Gak ada nomor',
  'cc.inst_total': 'Total',
  'kpr.delete_confirm': 'Hapus "{label}"? Gak bisa dibalikin.',
  'kpr.this_sim': 'simulasi ini',
  'kpr.extra_count': '{n} catatan',
  'kpr.remain_tenor': 'Sisa tenor',
  'kpr.month_n': '{n} bulan',
  'kpr.unit_bln': 'bln',
  'reports.uncategorized_n': '{n} kategori belum ada anggarannya',
  'kpr.extra_timeline': 'Bulan ke-{month} • {amount}',
  'tx.page_n': 'Hal {page} / {total}',
  'profile.admin_badge': '(admin)',
  'tx.owner_change': 'Ganti pemilik',
  'tx.sort_title': 'Urutin',
  'register.failed': 'Gagal',
  'bank.inbox_title': 'Dari bank',
  'bank.inbox_empty': 'Belum ada draf dari notifikasi bank',
  'bank.enable': 'Nyalain akses notifikasi',
  'bank.enable_hint': 'WealthTrack cuma baca notif app bank di HP ini. Gak minta sandi bank.',
  'bank.confirm': 'Catat',
  'bank.reject': 'Abaikan',
  'bank.unparsed': 'Nominal belum kebaca. Cek teksnya dulu.',
  'bank.saved': 'Kesimpen dari notif bank',
  'bank.rejected': 'Draf diabaikan',
  'profile.bank_inbox': 'Dari bank',
  'bank.status_saved': 'Sudah dicatat',
  'bank.status_skipped': 'Diabaikan',
  'bank.delete_confirm': 'Hapus draf notif ini? Transaksi yang sudah dicatat gak kehapus.',
  'bank.deleted': 'Notif dihapus',
  'bank.pick_category': 'Pilih kategori',
  'bank.pick_suggested': 'Saran otomatis',
  'bank.internal': 'Transfer sendiri',
  'bank.internal_hint': 'Nominal sama, beda bank. Gak dihitung belanja.',
  'bank.paste_title': 'Tempel teks notif',
  'bank.paste_hint': 'Buat iOS, atau kalau listener kelewat. Pilih bank, tempel teks, kirim.',
  'bank.paste_send': 'Kirim ke inbox',
  'bank.ios_hint': 'iOS gak bisa baca notif app lain. Tempel atau share teksnya ke sini.',
  'home.bank_draft': 'Draf dari bank',
  'bank.listen_apps': 'App yang didengar',
  'bank.listen_save': 'Simpan',
  'bank.listen_search': 'Cari nama atau package…',
  'bank.listen_hint': 'Cuma app yang terpasang. Default 16 bank/e-wallet yang ada di HP; yang belum diinstall dilewati.',
  'bank.no_amount': 'Teks ini gak ada nominal. Tempel notif yang ada Rp-nya.',
  'profile.language': 'Bahasa',
  'profile.lang_id': 'Indonesia',
  'profile.lang_en': 'English',
  'cat.n.food': 'Makanan & Minuman',
  'cat.n.transport': 'Transportasi & Bensin',
  'cat.n.shopping': 'Belanja Bulanan',
  'cat.n.entertainment': 'Hiburan',
  'cat.n.bills': 'Tagihan & Cicilan',
  'cat.n.health': 'Kesehatan',
  'cat.n.education': 'Pendidikan',
  'cat.n.savings': 'Tabungan & Investasi',
  'cat.n.baby': 'Kebutuhan Bayi/Anak',
  'cat.n.expense.other': 'Lainnya',
  'cat.n.expense.transfer': 'Transfer',
  'cat.n.expense.emergency': 'Dana Darurat',
  'cat.n.home': 'Kebutuhan Rumah',
  'cat.n.hobby': 'Hobi & Belajar',
  'cat.n.protein': 'Protein, Buah, dan Sayuran',
  'cat.n.personal': 'Kebutuhan Pribadi',
  'cat.n.salary': 'Gaji',
  'cat.n.freelance': 'Freelance',
  'cat.n.bonus': 'Bonus & THR',
  'cat.n.withdrawal': 'Penarikan Tabungan & Investasi',
  'cat.n.income.other': 'Lainnya',
  'cat.n.income.transfer': 'Transfer',
  'cat.n.income.emergency': 'Dana Darurat',
  'cat.n.investment': 'Hasil Investasi',
  'onboarding.choose': 'Pilih bahasa',
  'onboarding.choose_en': 'Choose a language',
  'onboarding.hint': 'Bisa diganti lagi di Profil.',
  'onboarding.next': 'Lanjut',
  'onboarding.start': 'Yuk mulai',
  'onboarding.p1_title': 'Catat duit, tanpa drama',
  'onboarding.p1_sub': 'Pengeluaran dan pemasukan ke satu tempat. Santai aja.',
  'onboarding.p2_title': 'Notif bank jadi catatan',
  'onboarding.p2_sub': 'Catat dari notifikasi. Gak minta sandi bank.',
  'err.generic': 'Ada yang gak beres. Coba lagi ya.',
  'err.validation': 'Data gak valid. Cek isian kamu ya.',
  'err.network': 'Gak ada internet. Cek koneksi, coba lagi.',
  'err.session': 'Sesi habis. Masuk lagi ya.',
  'err.rate_limit': 'Kebanyakan request. Tunggu sebentar ya.',
  'err.credentials': 'Username atau password salah',
};

String t(String key) {
  final fb = activeUiLocale == 'en-US' ? copyFallbackEn : copyFallback;
  return remoteCopy[key] ?? fb[key] ?? key;
}

String catLabel({required String name, String? copyKey}) {
  final k = (copyKey ?? '').trim();
  if (k.isEmpty) return name;
  return t(k);
}

String activeUiLocale = 'id-ID';

Map<String, String> remoteCopy = <String, String>{};

void applyRemoteCopy(Map<String, String> incoming) {
  remoteCopy = Map<String, String>.from(incoming);
}
