/// Copy ID — ramah, santai. Source of truth until GET /ui/bootstrap.
const Map<String, String> copyFallback = {
  'home.hero_title': 'Uang kamu',
  'home.hero_sub': 'Rekap pribadi, dari awal sampai sekarang',
  'home.income': 'Masuk',
  'home.expense': 'Keluar',
  'home.greeting': 'Hai',
  'home.subtitle': 'Saldo kamu, sepanjang waktu',
  'home.savings': 'Tabungan',
  'home.emergency': 'Dana darurat',
  'home.debt_running': 'Utang jalan',
  'home.ai': 'Teman AI',
  'home.ai_sub': 'Nanya apa aja soal duit',
  'home.debt_hub': 'Catatan utang',
  'home.debt_hub_sub': 'KPR & kartu kredit',
  'home.recent': 'Baru aja',
  'home.see_all': 'Lihat semua',
  'home.empty_tx': 'Belum ada transaksi. Yuk catat yang pertama!',
  'nav.dashboard': 'Beranda',
  'nav.transactions': 'Transaksi',
  'nav.budgets': 'Anggaran',
  'nav.reports': 'Laporan',
  'nav.profile': 'Profil',
  'tx.title': 'Transaksi',
  'tx.search': 'Cari catatan…',
  'tx.filter_all': 'Semua',
  'tx.filter_out': 'Keluar',
  'tx.filter_in': 'Masuk',
  'tx.categories': 'Kategori',
  'tx.date_specific': 'Tanggal tertentu',
  'tx.date_range': 'Rentang tanggal',
  'tx.delete': 'Hapus transaksi?',
  'tx.empty': 'Sepi. Belum ada yang tercatat.',
  'tx.add': 'Catat transaksi',
  'tx.new': 'Catatan baru',
  'tx.edit_title': 'Ubah catatan',
  'tx.kind_out': 'KELUAR',
  'tx.kind_in': 'MASUK',
  'tx.for': 'Untuk apa',
  'tx.for_hint': 'Sate padang, Grab, gaji…',
  'tx.date': 'Tanggal',
  'tx.note_opt': 'Catatan (opsional)',
  'tx.note_hint': 'Tambah catatan…',
  'tx.update': 'Simpan perubahan',
  'tx.scan_title': 'Ambil struk',
  'tx.scan_sub': 'Kamera atau dari galeri',
  'tx.recorded': 'Tercatat',
  'tx.updated': 'Sudah diubah',
  'tx.amount_err': 'Isi jumlah dulu',
  'tx.cat_err': 'Pilih kategori dulu',
  'tx.save_fail': 'Gagal simpan. Coba lagi.',
  'tx.processing': 'Struk lagi diproses…',
  'tx.processing_sub': 'Sebentar ya',
  'tx.photo': 'Fotoin struk',
  'tx.gallery': 'Ambil dari galeri',
  'budget.title': 'Anggaran',
  'budget.delete': 'Hapus anggaran?',
  'budget.empty': 'Belum pasang limit. Yuk bikin biar gak jebol.',
  'report.title': 'Laporan',
  'profile.title': 'Profil',
  'profile.logout': 'Keluar',
  'profile.logout_q': 'Yakin mau keluar dulu?',
  'profile.delete_account': 'Hapus akun',
  'debt.title': 'Catatan utang',
  'debt.kpr': 'Rumah (KPR)',
  'debt.kpr_sub': 'Hitung cicilan, cobain bunga beda-beda. Santai, ini simulasi.',
  'debt.cc': 'Kartu kredit',
  'debt.cc_sub': 'Jejak belanja, cicilan, dan tanggal tagihan.',
  'kpr.title': 'Simulasi KPR',
  'kpr.new': 'KPR baru',
  'kpr.delete': 'Hapus simulasi?',
  'kpr.extra': 'Bayar lebih',
  'cc.title': 'Kartu kredit',
  'cc.add': 'Tambah kartu',
  'cc.delete': 'Hapus kartu?',
  'ai.title': 'Teman AI',
  'ai.disclaimer': 'Ini saran mesin, bukan nasihat keuangan resmi ya.',
  'auth.login': 'Masuk',
  'auth.register': 'Daftar',
  'auth.hi': 'Hai lagi',
  'auth.tagline': 'Catat duit, tanpa drama',
  'auth.username': 'Username',
  'auth.email': 'Email',
  'auth.password': 'Kata sandi',
  'auth.password_again': 'Ulangi sandi',
  'auth.display_name': 'Nama tampilan',
  'auth.otp': 'Kode OTP',
  'auth.otp_hint': '6 digit dari email',
  'auth.send_otp': 'Kirim kode',
  'auth.sending_otp': 'Lagi dikirim…',
  'auth.otp_sent': 'Kode udah dikirim ke emailmu',
  'auth.register_hi': 'Yuk daftar',
  'auth.register_sub': 'Sebentar aja, terus bisa catat duit.',
  'auth.have_account': 'Sudah punya akun? Masuk aja',
  'auth.no_account': 'Belum punya akun? Daftar dulu',
  'auth.err_user': 'Minimal 3 huruf',
  'auth.err_pass': 'Minimal 6 karakter',
  'auth.err_email': 'Emailnya belum bener',
  'auth.err_display': 'Nama tampilan wajib diisi',
  'auth.err_match': 'Sandi belum sama',
  'auth.err_otp': 'Isi 6 digit dulu',
  'common.cancel': 'Batal',
  'common.save': 'Simpan',
  'common.delete': 'Hapus',
  'common.retry': 'Coba lagi',
  'common.share_hh': 'Biar keluarga juga lihat',
  'common.share_hh_sub': 'Kelihatan buat semua anggota rumah',
  'cat.manage': 'Atur kategori',
  'transfer.title': 'Pindahin saldo',
  'transfer.confirm': 'Kirim sekarang?',
};

String t(String key) => copyFallback[key] ?? key;
