"""English ui_copy seed (en-US). Keys must match COPY_ID."""
from __future__ import annotations

COPY_EN: dict[str, str] = {
    'home.hero_title': 'Your money',
    'home.hero_sub': 'Personal recap, from the start until now',
    'home.income': 'Income',
    'home.expense': 'Expense',
    'home.greeting': 'Hi',
    'home.greeting_sub': 'Your balance, all time',
    'home.savings': 'Savings',
    'home.emergency': 'Emergency fund',
    'home.debt_running': 'Active debt',
    'home.ai': 'AI buddy',
    'home.ai_sub': 'Ask anything about money',
    'home.debt_hub': 'Debt notes',
    'home.debt_hub_sub': 'Mortgage & credit cards',
    'home.recent': 'Just now',
    'home.see_all': 'See all',
    'home.empty_tx': 'No transactions yet. Log the first one!',
    'nav.dashboard': 'Home',
    'nav.transactions': 'Transactions',
    'nav.budgets': 'Budgets',
    'nav.reports': 'Reports',
    'nav.profile': 'Profile',
    'tx.title': 'Transactions',
    'tx.search': 'Search notes…',
    'tx.filter_all': 'All',
    'tx.filter_out': 'Expense',
    'tx.filter_in': 'Income',
    'tx.categories': 'Categories',
    'tx.sort': 'Sort',
    'tx.sort_newest': 'Newest',
    'tx.sort_oldest': 'Oldest',
    'tx.sort_high': 'Largest amount',
    'tx.sort_low': 'Smallest amount',
    'tx.date': 'Date',
    'tx.date_specific': 'Specific date',
    'tx.date_range': 'Date range',
    'tx.date_clear': 'Clear filter',
    'tx.delete': 'Delete this transaction?',
    'tx.empty': 'Quiet. Nothing logged yet.',
    'tx.add': 'Log a transaction',
    'tx.new': 'New entry',
    'tx.edit_title': 'Edit entry',
    'tx.kind_out': 'EXPENSE',
    'tx.kind_in': 'INCOME',
    'tx.for': 'What for',
    'tx.for_hint': 'Padang satay, Grab, salary…',
    'tx.note_opt': 'Note (optional)',
    'tx.note_hint': 'Add a note…',
    'tx.update': 'Save changes',
    'tx.scan_title': 'Scan receipt',
    'tx.scan_sub': 'Camera or gallery',
    'tx.recorded': 'Logged',
    'tx.updated': 'Updated',
    'tx.amount_err': 'Enter an amount first',
    'tx.cat_err': 'Pick a category first',
    'tx.save_fail': 'Couldn’t save. Try again.',
    'tx.processing': 'Reading the receipt…',
    'tx.processing_sub': 'Hang on',
    'tx.photo': 'Snap the receipt',
    'tx.gallery': 'Pick from gallery',
    'budget.title': 'Budgets',
    'budget.delete': 'Delete this budget?',
    'budget.empty': 'No limits yet. Set some so you don’t blow it.',
    'budget.empty_title': 'No budget this month',
    'budget.empty_hint': 'Tap + to set a limit per category',
    'budget.suggest_btn': 'Ask for ideas',
    'budget.overview': 'Budget overview',
    'budget.total': 'Total budget',
    'budget.spent': 'Spent',
    'budget.remaining': 'Left',
    'budget.income': 'Total income',
    'budget.over_by': 'Budget is bigger than income, over by {n}',
    'budget.covered': 'Income covers every budget ({n} left)',
    'budget.shortfall': 'Short {n}',
    'budget.outside': 'Outside budget',
    'budget.outside_hint': 'Spend in a category with no limit. Set one to track it.',
    'budget.edit': 'Edit budget',
    'budget.set': 'Set a monthly limit',
    'budget.pick_cat': 'Pick a category',
    'budget.limit': 'Monthly limit',
    'budget.cycle_day': 'Cycle start date',
    'budget.pick_day': 'Pick a date',
    'budget.day_n': 'Day {n}',
    'budget.cycle_hint': 'Spend is counted from this date last month until the day before this date this month.',
    'budget.update': 'Save changes',
    'budget.save': 'Set budget',
    'budget.remove_q': 'Delete the {c} budget?',
    'budget.over_by_short': 'Over {n}',
    'budget.exhausted': 'Limit used up',
    'budget.remaining_n': '{n} left',
    'report.title': 'Reports',
    'profile.title': 'Profile',
    'profile.cycle_day': 'Cycle start date',
    'profile.cycle_hint': 'Your billing cycle runs from day {n} until day {n-1} next month.',
    'profile.edit': 'Edit profile',
    'profile.change_pass': 'Change password',
    'profile.sec_account': 'Account',
    'profile.sec_features': 'Features',
    'profile.sec_cycle': 'Billing cycle',
    'profile.sec_look': 'Look',
    'profile.sec_actions': 'Account actions',
    'profile.debt_tracker': 'Debt notes',
    'profile.copy_admin': 'Manage copy',
    'profile.copy_search': 'Search key or text…',
    'profile.config_admin': 'Config settings',
    'profile.config_format': 'Money format',
    'profile.config_prefix': 'Prefix',
    'profile.config_group': 'Thousands separator',
    'profile.config_decimal': 'Decimal separator',
    'profile.config_flags': 'Feature flags',
    'profile.config_home_flag': 'Personal all-time home (true/false)',
    'profile.config_theme': 'Theme colors',
    'profile.config_theme_hint': 'Contrast-audited palettes. Pick, save, colors update live.',
    'profile.edit_name': 'Edit display name',
    'profile.name_hint': 'New display name',
    'profile.cur_pass': 'Current password',
    'profile.new_pass': 'New password',
    'profile.confirm_pass': 'Repeat new password',
    'profile.required': 'Required',
    'profile.theme_system': 'Match system',
    'profile.theme_light': 'Light',
    'profile.theme_dark': 'Dark',
    'profile.delete_forever': 'Delete forever',
    'hh.title': 'Household',
    'hh.join': 'Join a household',
    'hh.join_btn': 'Join',
    'hh.joining': 'Joining…',
    'hh.invite_code': 'Invite code',
    'hh.create': 'Create a household',
    'hh.create_btn': 'Create',
    'hh.create_new': 'Create new',
    'hh.name': 'Household name',
    'hh.default_name': 'Household',
    'hh.members': 'Members',
    'profile.cycle_pill': 'Day {n}',
    'profile.family_n': '{n} people',
    'hh.join_hint': 'Enter the invite code from the household admin.',
    'hh.joined': 'Joined the household',
    'hh.created': 'Household created',
    'hh.code_copied': 'Invite code copied',
    'hh.code_label': 'Code {c}',
    'hh.invite_hint': 'e.g. ABC12345',
    'hh.name_hint': 'e.g. Filla household',
    'profile.delete_warn': 'Your account and all money notes are deleted for good. This cannot be undone.',
    'profile.delete_type': 'Type DELETE to confirm:',
    'profile.delete_word': 'DELETE',
    'profile.logout': 'Log out',
    'profile.logout_q': 'Log out for now?',
    'profile.delete_account': 'Delete account',
    'debt.title': 'Debt notes',
    'debt.kpr': 'Home (mortgage)',
    'debt.kpr_sub': 'Run installments, try different rates. It’s a simulation.',
    'debt.cc': 'Credit cards',
    'debt.cc_sub': 'Track spend, installments, and due dates.',
    'kpr.title': 'Mortgage sim',
    'kpr.new': 'New mortgage',
    'kpr.delete': 'Delete this simulation?',
    'kpr.extra': 'Pay extra',
    'kpr.no_schedule': 'No installment schedule yet',
    'cc.title': 'Credit cards',
    'cc.add': 'Add a card',
    'cc.delete': 'Delete this card?',
    'cc.del_txn': 'Delete this transaction?',
    'cc.del_inst': 'Delete this installment?',
    'cc.txn_gone': 'Transaction deleted',
    'cc.inst_gone': 'Installment deleted',
    'ai.title': 'AI buddy',
    'ai.disclaimer': 'This is machine advice, not official financial advice.',
    'ai.hint': 'Ask about money…',
    'auth.login': 'Log in',
    'auth.register': 'Sign up',
    'auth.hi': 'Hey, WealthTrack here',
    'auth.tagline': 'Log money, skip the drama',
    'auth.username': 'Username',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.password_again': 'Repeat password',
    'auth.display_name': 'Display name',
    'auth.otp': 'OTP code',
    'auth.otp_hint': '6 digits from email',
    'auth.send_otp': 'Send code',
    'auth.sending_otp': 'Sending…',
    'auth.otp_sent': 'Code sent to your email',
    'auth.register_hi': 'Let’s sign up',
    'auth.register_sub': 'A minute, then you can log money.',
    'auth.have_account': 'Already have an account? Log in',
    'auth.no_account': 'No account yet? Sign up',
    'auth.err_user': 'At least 3 characters',
    'auth.err_pass': 'At least 6 characters',
    'auth.err_email': 'Email doesn’t look right',
    'auth.err_display': 'Display name is required',
    'auth.err_match': 'Passwords don’t match',
    'auth.err_otp': 'Enter all 6 digits',
    'common.cancel': 'Cancel',
    'common.save': 'Save',
    'common.delete': 'Delete',
    'common.retry': 'Try again',
    'common.required': 'Required',
    'common.positive': 'Enter a number above 0',
    'common.share_hh': 'Show it to the household too',
    'common.share_hh_sub': 'Visible to every household member',
    'cat.manage': 'Manage categories',
    'transfer.title': 'Move balance',
    'transfer.recipients': 'Recipients',
    'transfer.add_hint': 'Tap Add to pick a recipient',
    'transfer.confirm': 'Send now?',
    'transfer.send': 'Send',
    'transfer.sending': 'Working…',
    'transfer.no_members': 'No household members yet',
    'transfer.ok': 'Done! {n} transaction pairs logged.',
    'transfer.fail': 'Couldn’t send',
    'transfer.amount_positive': 'Amount for {name} must be above 0',
    'transfer.add_recipient': 'Add at least one recipient',
    'transfer.add': 'Add',
    'profile.updated': 'Profile saved',
    'profile.pass_ok': 'Password changed',
    'sort.title': 'Sort',
    'sort.newest': 'Newest',
    'sort.oldest': 'Oldest',
    'sort.highest': 'Largest',
    'sort.lowest': 'Smallest',
    'sort.name_az': 'Name A–Z',
    'sort.name_za': 'Name Z–A',
    'tx.deleted': 'Transaction deleted',
    'tx.del_fail': 'Couldn’t delete the transaction',
    'tx.no_other_member': 'No other household members yet',
    'common.edit': 'Edit',
    'common.change_owner': 'Change owner',
    'common.new': 'Create new',
    'suggest.title': 'Budget ideas',
    'suggest.empty': 'No ideas yet',
    'suggest.empty_sub': 'Log some transactions first, then I’ll suggest limits.',
    'suggest.picked': 'selected',
    'suggest.all': 'Select all',
    'suggest.clear': 'Clear',
    'suggest.apply': 'Apply',
    'suggest.avg': 'Average',
    'suggest.existing': 'Already set',
    'suggest.amount': 'Suggested',
    'report.income': 'Income',
    'report.expense': 'Expense',
    'report.balance': 'Left',
    'report.savings_rate': 'Savings',
    'report.daily_avg': 'Daily average',
    'report.vs_budget': 'Budget vs actual',
    'report.by_cat': 'By category',
    'report.compare_cat': 'Compare categories',
    'report.trend': 'Monthly trend',
    'report.daily': 'By day',
    'report.hh_split': 'Household split',
    'report.hh_cat': 'Household categories',
    'report.hh_daily': 'Household daily',
    'report.export': 'Download a year of Excel',
    'cat.add': 'New category',
    'cat.edit': 'Edit category',
    'cat.name': 'Name',
    'cat.icon': 'Icon',
    'cat.icon_search': 'Search icons (id / name)',
    'cat.keywords': 'Keywords',
    'cat.keywords_hint': 'separate with commas',
    'cat.type': 'Type',
    'cat.default_locked': 'Built-in categories can’t be changed.',
    'cat.save': 'Save',
    'cat.create': 'Add',
    'cat.empty': 'No categories yet',
    'cat.search': 'Search categories…',
    'cat.delete_confirm': 'Delete this category? Categories already used on transactions stay and can’t be deleted.',
    'cat.fail': 'Failed',
    'home.empty_tx_short': 'No transactions yet',
    'cc.summary': 'Summary',
    'cc.empty': 'No credit cards yet',
    'cc.empty_tx': 'No transactions yet',
    'cc.empty_installments': 'No installments yet',
    'cc.proj_next': 'Next month projection',
    'kpr.extra_payment': 'Extra payment',
    'kpr.schedule': 'Installment schedule',
    'kpr.extra_detail': 'Extra payment detail',
    'kpr.compare': 'See comparison',
    'kpr.pick_option': 'Pick what you want',
    'kpr.diff': 'Difference',
    'kpr.extra_deleted': 'Extra payment deleted',
    'kpr.empty': 'No mortgage simulation yet',
    'cat.empty_picker': 'No categories yet',
    'common.close': 'Close',
    'common.result': 'Result',
    'common.calculate': 'Calculate',
    'common.add_period': 'Add a period',
    'common.year_n': '{n} years',
    'common.day_n_short': 'Day {n}',
    'common.from_month': 'From (mo)',
    'common.to_month': 'To (mo)',
    'common.rate_pct': 'Rate %',
    'common.type': 'Type',
    'common.fixed': 'Fixed',
    'common.floating': 'Floating',
    'common.graduated': 'Stepped',
    'common.mix': 'Mix',
    'common.total': 'Total',
    'common.from': 'From',
    'common.apply': 'Apply',
    'common.clear_all': 'Clear all',
    'common.all_cat': 'All categories',
    'common.filter_cat': 'Filter categories',
    'common.select_owner': 'Pick a new owner',
    'common.owner_changed': 'Owner changed to {name}',
    'common.failed': 'Failed',
    'common.failed_download': 'Download failed',
    'common.making_file': 'Building the file…',
    'common.export_year': 'Export WealthTrack {year}',
    'common.thinking': 'Thinking…',
    'common.try_again': 'Failed — tap to try again',
    'common.not_found': 'Not found',
    'common.empty': 'Empty',
    'common.saved': 'Saved',
    'common.saved_live': 'Saved. Live, no rebuild.',
    'common.check_input': 'Check the fields again.',
    'common.delete_fail': 'Couldn’t delete',
    'ai.sample1': '"How much did I spend on food this month?"',
    'ai.sample2': '"Give me a savings tip"',
    'cc.tab_txn': 'Transactions',
    'cc.tab_inst': 'Installments',
    'cc.card_saved': 'Card saved',
    'cc.inst_saved': 'Installment saved',
    'cc.inst_add': 'Add installment',
    'cc.total_positive': 'Total must be above 0',
    'cc.monthly_positive': 'Monthly installment must be above 0',
    'cc.card_hint': 'e.g. Mandiri Visa Platinum',
    'cc.last4_hint': 'e.g. 1234',
    'cc.inst_hint': 'e.g. MacBook installment',
    'cc.months_hint': 'e.g. 12',
    'cc.amount_hint': 'Rp 0',
    'cc.desc_label': 'Description',
    'cc.desc_hint': 'e.g. shopping',
    'cc.amount_label': 'Amount',
    'cc.date_label': 'Date',
    'cc.not_found': 'Card not found',
    'cc.delete_confirm_body': 'Delete "{label}"? This cannot be undone.',
    'kpr.house_price': 'House price',
    'kpr.loan': 'Loan',
    'kpr.installment': 'Installment / month',
    'kpr.total_interest': 'Total interest',
    'kpr.total_payment': 'Total paid',
    'kpr.sim_not_found': 'Simulation not found',
    'kpr.sim_deleted': 'Simulation deleted',
    'kpr.sim_delete_fail': 'Couldn’t delete the simulation',
    'kpr.sim_saved': 'Simulation saved',
    'kpr.fill_price_dp': 'Fill house price and down payment first',
    'kpr.calc_failed': 'Couldn’t calculate. Try again',
    'kpr.loan_positive': 'Loan amount must be above 0',
    'kpr.name_hint': 'e.g. Dream house',
    'kpr.rate_hint': 'e.g. 9.0',
    'kpr.rate_low_hint': 'e.g. 7.0',
    'kpr.increment_hint': 'e.g. 0.5',
    'kpr.months_hint': 'e.g. 12',
    'kpr.extra_saved': 'Extra payment saved',
    'kpr.extra_fail': 'Couldn’t set the extra payment',
    'kpr.extra_amount': 'Extra payment amount (Rp)',
    'kpr.extra_apply_month': 'Apply in month',
    'kpr.option_a': 'A. Smaller installment',
    'kpr.option_a_sub': 'Same tenor, lower installment',
    'kpr.option_b': 'B. Shorter tenor',
    'kpr.option_b_sub': 'Same installment, paid off sooner',
    'kpr.period_label': 'New tenor',
    'kpr.period_n': 'Period {n}',
    'kpr.interest_saved': 'Interest saved',
    'kpr.paid_off': 'Paid off',
    'kpr.date_in_month': 'Day of month',
    'home.savings_pocket': 'Savings',
    'home.emergency_pocket': 'Emergency fund',
    'profile.saved': 'Profile saved',
    'profile.cycle_saved': 'Billing cycle saved',
    'profile.admin': 'admin',
    'debt.empty_hint': 'Pick what to handle. Relax — these are notes, not the bank.',
    'hh.member_badge': '🏠 Member',
    'cc.empty_add': 'Tap + to add a credit card',
    'cc.delete_card': 'Delete "{label}"? Its transactions and installments go too.',
    'cc.inst_note': '{count} installments · {amount} estimated',
    'cc.inst_progress': '{done} / {total} months',
    'kpr.empty_add': 'Tap + for your first mortgage sim',
    'kpr.due_label': 'Month {month} of {total} · {amount} due',
    'kpr.extra_intro': 'Extra payments cut principal right away. Pick a smaller installment or a shorter tenor.',
    'kpr.extra_pick': 'Both options shrink remaining principal. Pick what fits.',
    'kpr.extra_result': 'Installment: {installment}/month smaller (Option A) · Tenor: {months} months sooner (Option B)',
    'kpr.extra_delete': 'Delete extra payment {amount} in month {month}? The schedule is recalculated. This cannot be undone.',
    'kpr.no_extra': 'No extra payments yet. Tap the money icon above to add one.',
    'kpr.extra_applied': 'New installment & tenor apply {start} — {end}',
    'kpr.interest_year': 'Interest: {amount}',
    'kpr.year_label': 'Year {n}',
    'tx.delete_confirm': 'Delete "{label}"? This cannot be undone.',
    'tx.this_note': 'this note',
    'home.ocr_processing': '{count} transactions are processing…',
    'home.member_count': '{n} people',
    'reports.empty_month': 'Quiet month, nothing logged',
    'profile.app_version': 'WealthTrack v1.0.0',
    'cc.inst_active': 'Active installments',
    'cc.per_month': 'Per month',
    'cc.name_label': 'Card name',
    'cc.last4_label': 'Last 4 digits (optional)',
    'cc.limit_label': 'Credit limit',
    'cc.monthly_label': 'Installment / month',
    'cc.inst_months_label': 'Number of months',
    'cc.start_month_label': 'Start month',
    'kpr.name_label': 'Simulation name',
    'kpr.dp_label': 'Down payment (DP)',
    'kpr.loan_auto': 'Loan (auto)',
    'kpr.tenor_label': 'Tenor',
    'kpr.first_label': 'First installment',
    'kpr.due_date_label': 'Due date',
    'kpr.type_label': 'Rate type',
    'kpr.base_rate_label': 'Base rate (%)',
    'kpr.incr_label': 'Increase per period (%)',
    'kpr.period_months_label': 'Period length (months)',
    'kpr.periods_label': 'Rate periods',
    'cc.total_limit': 'Total limit',
    'cc.due_label': 'Due',
    'cc.bill_label': 'Statement date',
    'cc.this_card': 'this card',
    'cc.no_number': 'No number',
    'cc.inst_total': 'Total',
    'kpr.delete_confirm': 'Delete "{label}"? This cannot be undone.',
    'kpr.this_sim': 'this simulation',
    'kpr.extra_count': '{n} notes',
    'kpr.remain_tenor': 'Remaining tenor',
    'kpr.month_n': '{n} months',
    'kpr.unit_bln': 'mo',
    'reports.uncategorized_n': '{n} categories have no budget',
    'kpr.extra_timeline': 'Month {month} • {amount}',
    'tx.page_n': 'Page {page} / {total}',
    'profile.admin_badge': '(admin)',
    'tx.owner_change': 'Change owner',
    'tx.sort_title': 'Sort',
    'register.failed': 'Failed',
    'bank.inbox_title': 'From the bank',
    'bank.inbox_empty': 'No drafts from bank notifications yet',
    'bank.enable': 'Turn on notification access',
    'bank.enable_hint': 'WealthTrack only reads bank-app notifications on this phone. No bank password.',
    'bank.confirm': 'Log',
    'bank.reject': 'Skip',
    'bank.unparsed': 'Amount wasn’t read. Check the text.',
    'bank.saved': 'Saved from a bank notification',
    'bank.rejected': 'Draft skipped',
    'profile.bank_inbox': 'From the bank',
    'bank.status_saved': 'Logged',
    'bank.status_skipped': 'Skipped',
    'bank.delete_confirm': 'Delete this notification draft? Transactions already logged stay.',
    'bank.deleted': 'Notification deleted',
    'bank.pick_category': 'Pick a category',
    'bank.pick_suggested': 'Auto suggestion',
    'bank.internal': 'Own-account transfer',
    'bank.internal_hint': 'Same amount, different bank. Not counted as spending.',
    'bank.paste_title': 'Paste notification text',
    'bank.paste_hint': 'For iOS, or if the listener missed it. Pick a bank, paste text, send.',
    'bank.paste_send': 'Send to inbox',
    'bank.ios_hint': 'iOS can’t read other apps’ notifications. Paste or share the text here.',
    'home.bank_draft': 'Bank draft',
    'bank.listen_apps': 'Apps to listen to',
    'bank.listen_save': 'Save',
    'bank.listen_search': 'Search name or package…',
    'bank.listen_hint': 'Installed apps only. Default is the 16 bank/e-wallet apps on the phone; missing ones are skipped.',
    'bank.no_amount': 'This text has no amount. Paste a notification that includes Rp.',
    'profile.language': 'Language',
    'profile.lang_id': 'Indonesia',
    'profile.lang_en': 'English',
    'cat.n.food': 'Food & drinks',
    'cat.n.transport': 'Transport',
    'cat.n.shopping': 'Monthly shopping',
    'cat.n.entertainment': 'Entertainment',
    'cat.n.bills': 'Bills',
    'cat.n.health': 'Health',
    'cat.n.education': 'Education',
    'cat.n.savings': 'Savings & investing',
    'cat.n.baby': 'Baby & kids',
    'cat.n.expense.other': 'Other',
    'cat.n.expense.transfer': 'Transfer',
    'cat.n.expense.emergency': 'Emergency fund',
    'cat.n.home': 'Home',
    'cat.n.hobby': 'Hobbies & learning',
    'cat.n.protein': 'Protein, fruit & veg',
    'cat.n.personal': 'Personal',
    'cat.n.salary': 'Salary',
    'cat.n.freelance': 'Freelance',
    'cat.n.bonus': 'Bonus & THR',
    'cat.n.withdrawal': 'Withdrawal',
    'cat.n.income.other': 'Other',
    'cat.n.income.transfer': 'Transfer',
    'cat.n.income.emergency': 'Emergency fund',
    'cat.n.investment': 'Investment returns',
    'onboarding.choose': 'Choose a language',
    'onboarding.choose_en': 'Pilih bahasa',
    'onboarding.hint': 'You can change this later in Profile.',
    'onboarding.next': 'Next',
    'onboarding.start': "Let's go",
    'onboarding.p1_title': 'Log money, skip the drama',
    'onboarding.p1_sub': 'Income and spend in one place. Easy.',
    'onboarding.p2_title': 'Bank alerts become notes',
    'onboarding.p2_sub': 'Log from notifications. No bank password.',
}
