"""Seed rows for ui_copy / ui_config. Not the live catalog.

INSERT ... ON CONFLICT DO NOTHING — never overwrite live edits.
"""
from __future__ import annotations

COPY_ID: dict[str, str] = {
    'home.hero_title': 'Uang kamu',
    'home.hero_sub': 'Rekap pribadi, dari awal sampai sekarang',
    'home.income': 'Pemasukan',
    'home.expense': 'Pengeluaran',
    'home.greeting': 'Hai',
    'home.subtitle': 'Saldo kamu, sepanjang waktu',
    'home.savings': 'Simpanan',
    'home.emergency': 'Dana darurat',
    'home.debt_running': 'Utang jalan',
    'home.ai': 'Teman AI',
    'home.ai_sub': 'Nanya apa aja soal duit',
    'home.debt_hub': 'Catatan utang',
    'home.debt_hub_sub': 'KPR & kartu kredit',
    'home.recent': 'Baru aja',
    'home.see_all': 'Lihat semua',
    'home.empty_tx': 'Belum ada transaksi. Yuk catat yang pertama!',
    'nav.dashboard': 'Beranda',
    'nav.transactions': 'Transaksi',
    'nav.budgets': 'Anggaran',
    'nav.reports': 'Laporan',
    'nav.profile': 'Profil',
    'tx.title': 'Transaksi',
    'tx.search': 'Cari catatan…',
    'tx.filter_all': 'Semua',
    'tx.filter_out': 'Pengeluaran',
    'tx.filter_in': 'Pemasukan',
    'tx.categories': 'Kategori',
    'tx.sort': 'Urutkan',
    'tx.sort_newest': 'Terbaru',
    'tx.sort_oldest': 'Terlama',
    'tx.sort_high': 'Nominal besar',
    'tx.sort_low': 'Nominal kecil',
    'tx.date': 'Tanggal',
    'tx.date_specific': 'Tanggal tertentu',
    'tx.date_range': 'Rentang tanggal',
    'tx.date_clear': 'Hapus filter',
    'tx.delete': 'Hapus transaksi?',
    'tx.empty': 'Sepi. Belum ada yang tercatat.',
    'tx.add': 'Catat transaksi',
    'tx.new': 'Catatan baru',
    'tx.edit_title': 'Ubah catatan',
    'tx.kind_out': 'PENGELUARAN',
    'tx.kind_in': 'PEMASUKAN',
    'tx.for': 'Untuk apa',
    'tx.for_hint': 'Sate padang, Grab, gaji…',
    'tx.note_opt': 'Catatan (opsional)',
    'tx.note_hint': 'Tambah catatan…',
    'tx.update': 'Simpan perubahan',
    'tx.scan_title': 'Ambil struk',
    'tx.scan_sub': 'Kamera atau dari galeri',
    'tx.recorded': 'Tercatat',
    'tx.updated': 'Sudah diubah',
    'tx.amount_err': 'Isi jumlah dulu',
    'tx.cat_err': 'Pilih kategori dulu',
    'tx.save_fail': 'Gagal simpan. Coba lagi.',
    'tx.processing': 'Struk lagi diproses…',
    'tx.processing_sub': 'Sebentar ya',
    'tx.photo': 'Fotoin struk',
    'tx.gallery': 'Ambil dari galeri',
    'budget.title': 'Anggaran',
    'budget.delete': 'Hapus anggaran?',
    'budget.empty': 'Belum pasang limit. Yuk bikin biar gak jebol.',
    'budget.empty_title': 'Belum ada anggaran bulan ini',
    'budget.empty_hint': 'Tap + buat pasang limit per kategori',
    'budget.suggest_btn': 'Minta saran',
    'budget.overview': 'Ringkasan anggaran',
    'budget.total': 'Total anggaran',
    'budget.spent': 'Sudah dipakai',
    'budget.remaining': 'Sisa',
    'budget.income': 'Total pemasukan',
    'budget.over_by': 'Anggaran lebih besar dari pemasukan, lebihan {n}',
    'budget.covered': 'Pemasukan cukup buat semua anggaran (sisa {n})',
    'budget.shortfall': 'Kurang {n}',
    'budget.outside': 'Di luar anggaran',
    'budget.outside_hint': 'Ada pengeluaran di kategori yang belum dipasang limit. Pasang biar kepantau.',
    'budget.edit': 'Ubah anggaran',
    'budget.set': 'Pasang limit bulanan',
    'budget.pick_cat': 'Pilih kategori',
    'budget.limit': 'Limit bulanan',
    'budget.cycle_day': 'Tanggal mulai siklus',
    'budget.pick_day': 'Pilih tanggal',
    'budget.day_n': 'Tanggal {n}',
    'budget.cycle_hint': 'Pengeluaran dihitung dari tanggal ini bulan lalu sampai sehari sebelum tanggal ini bulan ini.',
    'budget.update': 'Simpan perubahan',
    'budget.save': 'Pasang anggaran',
    'budget.remove_q': 'Hapus anggaran {c}?',
    'budget.over_by_short': 'Lebih {n}',
    'budget.exhausted': 'Limit habis',
    'budget.remaining_n': 'Sisa {n}',
    'report.title': 'Laporan',
    'profile.title': 'Profil',
    'profile.cycle_day': 'Tanggal mulai siklus',
    'profile.cycle_hint': 'Siklus tagihan kamu jalan dari tanggal {n} sampai tanggal {n-1} bulan depan.',
    'profile.edit': 'Ubah profil',
    'profile.change_pass': 'Ganti sandi',
    'profile.sec_account': 'Setelan akun',
    'profile.sec_features': 'Fitur',
    'profile.sec_cycle': 'Siklus tagihan',
    'profile.sec_look': 'Tampilan',
    'profile.sec_actions': 'Aksi akun',
    'profile.debt_tracker': 'Catatan utang',
    'profile.edit_name': 'Ubah nama tampilan',
    'profile.name_hint': 'Nama tampilan baru',
    'profile.cur_pass': 'Sandi sekarang',
    'profile.new_pass': 'Sandi baru',
    'profile.confirm_pass': 'Ulangi sandi baru',
    'profile.required': 'Wajib diisi',
    'profile.theme_system': 'Ikut sistem',
    'profile.theme_light': 'Terang',
    'profile.theme_dark': 'Gelap',
    'profile.delete_forever': 'Hapus permanen',
    'hh.title': 'Keluarga',
    'hh.join': 'Gabung keluarga',
    'hh.join_btn': 'Gabung',
    'hh.joining': 'Lagi gabung…',
    'hh.invite_code': 'Kode undangan',
    'hh.create': 'Buat keluarga baru',
    'hh.create_btn': 'Buat',
    'hh.create_new': 'Buat baru',
    'hh.name': 'Nama keluarga',
    'hh.default_name': 'Keluarga',
    'hh.members': 'Anggota',
    'profile.cycle_pill': 'Tanggal {n}',
    'profile.family_n': '{n} orang',
    'hh.join_hint': 'Isi kode undangan dari admin keluarga.',
    'hh.joined': 'Gabung keluarga berhasil',
    'hh.created': 'Keluarga berhasil dibuat',
    'hh.code_copied': 'Kode undangan disalin',
    'hh.code_label': 'Kode {c}',
    'hh.invite_hint': 'contoh ABC12345',
    'hh.name_hint': 'contoh Keluarga Filla',
    'profile.delete_warn': 'Akun dan semua catatan duit kehapus permanen. Gak bisa dibalikin.',
    'profile.delete_type': 'Ketik HAPUS buat konfirmasi:',
    'profile.delete_word': 'HAPUS',
    'profile.logout': 'Keluar',
    'profile.logout_q': 'Yakin mau keluar dulu?',
    'profile.delete_account': 'Hapus akun',
    'debt.title': 'Catatan utang',
    'debt.kpr': 'Rumah (KPR)',
    'debt.kpr_sub': 'Hitung cicilan, cobain bunga beda-beda. Santai, ini simulasi.',
    'debt.cc': 'Kartu kredit',
    'debt.cc_sub': 'Jejak belanja, cicilan, dan tanggal tagihan.',
    'kpr.title': 'Simulasi KPR',
    'kpr.new': 'KPR baru',
    'kpr.delete': 'Hapus simulasi?',
    'kpr.extra': 'Bayar lebih',
    'kpr.no_schedule': 'Belum ada jadwal cicilan',
    'cc.title': 'Kartu kredit',
    'cc.add': 'Tambah kartu',
    'cc.delete': 'Hapus kartu?',
    'cc.del_txn': 'Hapus transaksi?',
    'cc.del_inst': 'Hapus cicilan?',
    'cc.txn_gone': 'Transaksi kehapus',
    'cc.inst_gone': 'Cicilan kehapus',
    'ai.title': 'Teman AI',
    'ai.disclaimer': 'Ini saran mesin, bukan nasihat keuangan resmi ya.',
    'ai.hint': 'Nanya soal duit…',
    'auth.login': 'Masuk',
    'auth.register': 'Daftar',
    'auth.hi': 'Halo sob, WealthTrack disini',
    'auth.tagline': 'Catat duit, tanpa drama',
    'auth.username': 'Username',
    'auth.email': 'Email',
    'auth.password': 'Kata sandi',
    'auth.password_again': 'Ulangi sandi',
    'auth.display_name': 'Nama tampilan',
    'auth.otp': 'Kode OTP',
    'auth.otp_hint': '6 digit dari email',
    'auth.send_otp': 'Kirim kode',
    'auth.sending_otp': 'Lagi dikirim…',
    'auth.otp_sent': 'Kode udah dikirim ke emailmu',
    'auth.register_hi': 'Yuk daftar',
    'auth.register_sub': 'Sebentar aja, terus bisa catat duit.',
    'auth.have_account': 'Sudah punya akun? Masuk aja',
    'auth.no_account': 'Belum punya akun? Daftar dulu',
    'auth.err_user': 'Minimal 3 huruf',
    'auth.err_pass': 'Minimal 6 karakter',
    'auth.err_email': 'Emailnya belum bener',
    'auth.err_display': 'Nama tampilan wajib diisi',
    'auth.err_match': 'Sandi belum sama',
    'auth.err_otp': 'Isi 6 digit dulu',
    'common.cancel': 'Batal',
    'common.save': 'Simpan',
    'common.delete': 'Hapus',
    'common.retry': 'Coba lagi',
    'common.required': 'Wajib diisi',
    'common.positive': 'Isi angka di atas 0',
    'common.share_hh': 'Biar keluarga juga lihat',
    'common.share_hh_sub': 'Kelihatan buat semua anggota keluarga',
    'cat.manage': 'Kelola kategori',
    'transfer.title': 'Pindahin saldo',
    'transfer.recipients': 'Penerima',
    'transfer.add_hint': 'Tap Tambah buat pilih penerima',
    'transfer.confirm': 'Kirim sekarang?',
    'transfer.send': 'Kirim',
    'transfer.sending': 'Lagi diproses…',
    'transfer.no_members': 'Belum ada anggota keluarga',
    'transfer.ok': 'Berhasil! {n} pasang transaksi tercatat.',
    'transfer.fail': 'Gagal kirim',
    'transfer.add_recipient': 'Tambah minimal satu penerima',
    'transfer.add': 'Tambah',
    'profile.updated': 'Profil kesimpen',
    'profile.pass_ok': 'Sandi berhasil diganti',
    'sort.title': 'Urutin',
    'sort.newest': 'Paling baru',
    'sort.oldest': 'Paling lama',
    'sort.highest': 'Paling gede',
    'sort.lowest': 'Paling kecil',
    'sort.name_az': 'Nama A–Z',
    'sort.name_za': 'Nama Z–A',
    'tx.deleted': 'Transaksi kehapus',
    'tx.del_fail': 'Gagal hapus transaksi',
    'tx.no_other_member': 'Belum ada anggota keluarga lain',
    'common.edit': 'Ubah',
    'common.change_owner': 'Ganti pemilik',
    'common.new': 'Buat baru',
    'suggest.title': 'Saran anggaran',
    'suggest.empty': 'Belum ada saran',
    'suggest.empty_sub': 'Catat transaksi dulu, nanti aku bikinin limitnya.',
    'suggest.picked': 'dipilih',
    'suggest.all': 'Pilih semua',
    'suggest.clear': 'Kosongin',
    'suggest.apply': 'Pasang',
    'suggest.avg': 'Rata-rata',
    'suggest.existing': 'Sudah ada',
    'suggest.amount': 'Usulan',
    'report.income': 'Pemasukan',
    'report.expense': 'Pengeluaran',
    'report.balance': 'Sisa',
    'report.savings_rate': 'Simpanan',
    'report.daily_avg': 'Rata-rata/hari',
    'report.vs_budget': 'Anggaran vs real',
    'report.by_cat': 'Per kategori',
    'report.compare_cat': 'Banding kategori',
    'report.trend': 'Tren bulanan',
    'report.daily': 'Per hari',
    'report.hh_split': 'Bagi keluarga',
    'report.hh_cat': 'Kategori keluarga',
    'report.hh_daily': 'Harian keluarga',
    'report.export': 'Unduh Excel setahun',
    'cat.add': 'Kategori baru',
    'cat.edit': 'Ubah kategori',
    'cat.name': 'Nama',
    'cat.icon': 'Ikon',
    'cat.icon_search': 'Cari ikon (id / nama)',
    'cat.keywords': 'Kata kunci',
    'cat.keywords_hint': 'pisah pakai koma',
    'cat.type': 'Tipe',
    'cat.default_locked': 'Kategori bawaan gak bisa diubah.',
    'cat.save': 'Simpan',
    'cat.create': 'Tambah',
    'cat.empty': 'Belum ada kategori',
    'cat.fail': 'Gagal',
}

THEME_LIGHT: dict[str, str] = {
    "background": "#FFF3EE",
    "surface": "#FFFFFF",
    "ink": "#4A3A48",
    "muted": "#9B8794",
    "line": "#F3E0D8",
    "accent": "#F3A6B8",
    "expense": "#E08B7C",
    "income": "#4EAE90",
    "warning": "#E8B86D",
    "heroFill": "#FFE8DC",
    "heroOn": "#4A3A48",
    "mint": "#9DD9C0",
    "lilac": "#D4C4F0",
    "butter": "#F6E3A1",
}

THEME_DARK: dict[str, str] = {
    "background": "#2A2430",
    "surface": "#3A3242",
    "ink": "#F7EEE8",
    "muted": "#C4B4BE",
    "line": "#4C4354",
    "accent": "#E9A0B2",
    "expense": "#F0A090",
    "income": "#7ED0B4",
    "warning": "#E8C47A",
    "heroFill": "#463848",
    "heroOn": "#F7EEE8",
    "mint": "#8FCFB6",
    "lilac": "#D4C4F0",
    "butter": "#E8D28A",
}

FORMAT: dict = {
    "currency": "IDR",
    "currency_prefix": "Rp",
    "group_sep": ".",
    "decimal_sep": ",",
}

FLAGS: dict = {
    "home_all_time": True,
}


async def seed_ui(conn) -> None:
    """Idempotent seed. ``conn`` is a raw asyncpg connection."""
    import json

    for key, value in COPY_ID.items():
        await conn.execute(
            """
            INSERT INTO ui_copy (key, locale, value)
            VALUES ($1, 'id-ID', $2)
            ON CONFLICT (key, locale) DO NOTHING
            """,
            key,
            value,
        )
    rows = {
        "locale": "id-ID",
        "format": FORMAT,
        "theme.light": THEME_LIGHT,
        "theme.dark": THEME_DARK,
        "flags": FLAGS,
    }
    for key, value in rows.items():
        await conn.execute(
            """
            INSERT INTO ui_config (key, value)
            VALUES ($1, $2::jsonb)
            ON CONFLICT (key) DO NOTHING
            """,
            key,
            json.dumps(value),
        )
